### ISSUE TITLE
Fix "download csv" on some browsers

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#107]
Users report on some browsers (notably Firefox and Safari) the "download csv" page only says "File downloaded" without opening the actual download box.

**Comment by jacomyma** [comment]
fixed by a shitty turnaround involving setTimeout twice -_-

**Comment by jschaeff** [comment]
Hi there, problem still happening on version 0.2.1 of hyphe.

**Comment by boogheta** [comment]
It is fixed in master, so it will be in a next release that should come up in the coming weeks
